- name: Allow remote connection to the docker daemon
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^(.*ExecStart=/usr/bin/dockerd.*)$'
    line: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://0.0.0.0:2375'
  notify: docker status
