all:
  hosts:
    u1:
      ansible_host: 192.168.33.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/qdnqn/vagrant/.vagrant/machines/u1/virtualbox/private_key
    u2:
      ansible_host: 192.168.33.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/qdnqn/vagrant/.vagrant/machines/u2/virtualbox/private_key