plugin: aws_ec2

aws_access_key: AKIAVFJSDN7HP4IA34YE
aws_secret_key: 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

regions:
  - us-east-2

hostnames:
# a list in order of precedence for hostname variables.
# 
  - dns-name
  - ip-address
  - tag:Name
  - private-ip-address

strict_permissions: False