apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-multitool-deployment
  labels:
    app: network-multitool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: network-multitool
  template:
    metadata:
      labels:
        app: network-multitool
    spec:
      containers:
      - name: network-multitool
        image: praqma/network-multitool:latest

