apiVersion: v1
kind: ReplicaSet
metadata:
  name: rs1
  labels:
    app: rs1-app
spec:
  selector:
    matchLabels:
      app: pod1-app
  replicas: 2
  template:
    metadata:
  name: pod1
  labels:
    app: pod1-app
spec:
  containers:
  - name: java
    image: tomee:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/tomee
      name: tomee_vol