apiVersion: v1
kind: Service
metadata:
  name: s1
spec:
  selector:
    app: pod1-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080