---
- name: Add new user playbook
  hosts: all
  become: yes
  vars: 
    usernames: 
      - qdnqn1
      - qdnqn2
      - qdnqn3
  tasks:
    - name: Add new user task
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ usernames }}"